<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hx</string>
	</array>
	<key>name</key>
	<string>HACS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(sort|scheme|attribute)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(token|fragment)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@[0-9]+|#[A-Za-z0-9]+)</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([A-Z][A-Za-z]*\()</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>entity.name.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#hash_symbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Z][A-Za-z]*)</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#special_characters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>hash_symbols</key>
		<dict>
			<key>match</key>
			<string>(@[0-9]+|#[A-Za-z0-9]*)</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<key>special_characters</key>
		<dict>
			<key>match</key>
			<string>[↑↓→]</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>⟦</string>
			<key>end</key>
			<string>⟧</string>
			<key>name</key>
			<string>string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>⟨</string>
					<key>end</key>
					<string>⟩</string>
					<key>name</key>
					<string>variable.parameter</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#hash_symbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#special_characters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.hacs</string>
	<key>uuid</key>
	<string>11503641-06bd-41df-82cf-eb75f93f5af1</string>
</dict>
</plist>
